spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  active:
    profile: dev
  application:
    name: pathfinder
#  cloud:
#    vault:
#      uri: http://127.0.0.1:8200
#      token: '00000000-0000-0000-0000-000000000000'
#      kv:
#        enabled: true
#  config:
#    import: vault://
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password:
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
#  resources: # Static resources
#    static-locations: file:src/main/resources/static/
#    cache:
#      period: 0

binding-result-package: org.springframework.validation.BindingResult

pathfinder:
  gpx-coordinates:
    migrate: false